GLOBAL_LIST_INIT(marine_gear_listed_products, list(
	/obj/item/implanter/skill/firearms = list(CAT_MARINE, "枪械技能植入器", 35, "cyan2"),
	/obj/item/implanter/skill/melee = list(CAT_MARINE, "近战技能植入器", 25, "cyan2"),
	/obj/item/implanter/skill/medical = list(CAT_MARINE, "医疗技能植入器", 20, "cyan2"),
	/obj/item/implanter/skill/engineer = list(CAT_MARINE, "工程技能植入器", 20, "cyan2"),
	/obj/item/implanter/skill/construct = list(CAT_MARINE, "建筑技能植入器", 20, "cyan2"),
	/obj/item/storage/backpack/marine/radiopack = list(CAT_MARINE, "无线电背包", 15, "orange"),
	/obj/item/stack/sandbags_empty/half = list(CAT_MARINE, "沙袋 x25", 5, "orange"),
	/obj/item/fulton_extraction_pack = list(CAT_MARINE, "富尔顿回收包", 15, "orange"),
	/obj/item/explosive/grenade = list(CAT_MARINE, "M40高爆双用途手雷", 2, "orange3"),
	/obj/item/explosive/grenade/sticky = list(CAT_MARINE, "M40粘性炸药手雷", 2, "orange3"),
	/obj/item/explosive/grenade/incendiary = list(CAT_MARINE, "M40高爆燃烧手雷", 2, "orange3"),
	/obj/item/explosive/grenade/m15 = list(CAT_MARINE, "M15破片手雷", 3, "orange3"),
	/obj/item/explosive/grenade/smokebomb/drain = list(CAT_MARINE, "M40-T烟雾手雷", 25, "orange3"),
	/obj/item/explosive/grenade/sticky/cloaker/tangle = list(CAT_MARINE, "M45-T绊足手雷", 20, "orange3"),
	/obj/structure/closet/crate/mortar_ammo/mortar_kit = list(CAT_MARINE, "迫击炮套件", 45, "orange3"),
	/obj/structure/closet/crate/mortar_ammo/howitzer_kit = list(CAT_MARINE, "榴弹炮套件", 45, "orange3"),
	/obj/structure/closet/crate/mortar_ammo/mlrs_kit = list(CAT_MARINE, "多管火箭炮套件", 45, "orange3"),
	/obj/item/reagent_containers/hypospray/autoinjector/oxycodone = list(CAT_MARINE, "羟考酮自动注射器", 10, "cyan"),
	/obj/item/reagent_containers/hypospray/autoinjector/synaptizine	 = list(CAT_MARINE, "突触素自动注射器", 15, "cyan"),
	/obj/vehicle/ridden/motorbike = list(CAT_MARINE, "自行车", 45, "blue"),
	/obj/item/sidecar = list(CAT_MARINE, "自行车挎斗", 15, "blue"),
	/obj/item/ammo_magazine/rifle/ar21/extended = list(CAT_MARINE, "AR-21加长弹匣", 15, "blue"),
	/obj/item/storage/briefcase/standard_magnum = list(CAT_MARINE, "R-76弹药箱", 25, "blue"),
))
