/obj/machinery/vending/cargo_supply
	name = "\improper 作战物资售卖机"
	desc = "用于分发特种和散装物资的大型售卖机. 仅限货运人员使用."
	icon_state = "requisitionop"
	icon_vend = "requisitionop-vend"
	icon_deny = "requisitionop-deny"
	wrenchable = FALSE
	products = list(
		"剩余特种装备" = list(
			/obj/item/pinpointer = 1,
			/obj/item/supply_beacon = 1,
			/obj/item/explosive/plastique = 5,
			/obj/item/fulton_extraction_pack = 2,
			/obj/item/clothing/suit/storage/marine/boomvest = 20,
			/obj/item/radio/headset/mainship/marine/alpha = -1,
			/obj/item/radio/headset/mainship/marine/bravo = -1,
			/obj/item/radio/headset/mainship/marine/charlie = -1,
			/obj/item/radio/headset/mainship/marine/delta = -1,
		),
		"采矿设备" = list(
			/obj/item/minerupgrade/automatic = 1,
			/obj/item/minerupgrade/reinforcement = 1,
			/obj/item/minerupgrade/overclock = 1,
		),
		"补给站基础" = list(
			/obj/item/paper/factoryhowto = -1,
			/obj/machinery/fabricator/gunpowder = 2,
			/obj/machinery/fabricator/junk = 1,
			/obj/machinery/assembler = 10,
			/obj/machinery/splitter = -1,
			/obj/item/stack/conveyor/thirty = -1,
			/obj/item/conveyor_switch_construct = -1,
		),
		"手榴弹箱" = list(
			/obj/item/storage/box/visual/grenade/frag = 1,
			/obj/item/storage/box/visual/grenade/incendiary = 2,
			/obj/item/storage/box/visual/grenade/m15 = 1,
			/obj/item/storage/box/visual/grenade/cloak = 1,
			/obj/item/storage/box/visual/grenade/sticky = 1,
			/obj/item/storage/box/visual/grenade/trailblazer = 1,
		),
		"弹药箱" = list(
			/obj/item/matter_ammo_box/light = -1,
			/obj/item/matter_ammo_box = -1,
			/obj/item/matter_ammo_box/big = -1,
			/obj/item/matter_ammo_box/giant = -1,
			/obj/item/shotgunbox = -1,
			/obj/item/shotgunbox/buckshot = -1,
			/obj/item/shotgunbox/flechette = -1,
			/obj/item/shotgunbox/tracker = -1,
			/obj/item/shotgunbox/blank = -1,
			/obj/item/storage/box/visual/magazine/compact/p14/full = -1,
			/obj/item/storage/box/visual/magazine/compact/p23/full = -1,
			/obj/item/storage/box/visual/magazine/compact/r44/full = -1,
			/obj/item/storage/box/visual/magazine/compact/p17/full = -1,
			/obj/item/storage/box/visual/magazine/compact/vp70/full = -1,
			/obj/item/storage/box/visual/magazine/compact/plasma_pistol/full = -1,
			/obj/item/storage/box/visual/magazine/compact/ar12/full = -1,
			/obj/item/storage/box/visual/magazine/compact/martini/full = -1,
			/obj/item/storage/box/visual/magazine/compact/lasrifle/marine/full = -1,
			/obj/item/storage/box/visual/magazine/compact/sh15/flechette/full = -1,
			/obj/item/storage/box/visual/magazine/compact/sh15/slug/full = -1,
			/obj/item/storage/box/visual/magazine/compact/dmr37/full = -1,
			/obj/item/storage/box/visual/magazine/compact/sr127/full = -1,
			/obj/item/storage/box/visual/magazine/compact/mg42/full = -1,
			/obj/item/storage/box/visual/magazine/compact/mg60/full = -1,
			/obj/item/storage/box/visual/magazine/compact/mg27/full = -1,
		),
		"机甲弹药" = list(
			/obj/item/mecha_ammo/vendable/pistol = -1,
			/obj/item/mecha_ammo/vendable/burstpistol = -1,
			/obj/item/mecha_ammo/vendable/smg = -1,
			/obj/item/mecha_ammo/vendable/burstrifle = -1,
			/obj/item/mecha_ammo/vendable/rifle = -1,
			/obj/item/mecha_ammo/vendable/shotgun = -1,
			/obj/item/mecha_ammo/vendable/lmg = -1,
			/obj/item/mecha_ammo/vendable/lightcannon = -1,
			/obj/item/mecha_ammo/vendable/heavycannon = -1,
			/obj/item/mecha_ammo/vendable/minigun = -1,
			/obj/item/mecha_ammo/vendable/sniper = -1,
			/obj/item/mecha_ammo/vendable/grenade = -1,
			/obj/item/mecha_ammo/vendable/flamer = -1,
			/obj/item/mecha_ammo/vendable/rpg = -1,
		)
	)
